/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package electrostore.db.model;

import com.liferay.portal.kernel.model.BaseModel;

import electrostore.db.service.persistence.Electrotype_EmployeePK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Electrotype_Employee service. Represents a row in the &quot;electrotype_employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>electrostore.db.model.impl.Electrotype_EmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>electrostore.db.model.impl.Electrotype_EmployeeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Electrotype_Employee
 * @generated
 */
@ProviderType
public interface Electrotype_EmployeeModel
	extends BaseModel<Electrotype_Employee> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a electrotype_ employee model instance should use the {@link Electrotype_Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this electrotype_ employee.
	 *
	 * @return the primary key of this electrotype_ employee
	 */
	public Electrotype_EmployeePK getPrimaryKey();

	/**
	 * Sets the primary key of this electrotype_ employee.
	 *
	 * @param primaryKey the primary key of this electrotype_ employee
	 */
	public void setPrimaryKey(Electrotype_EmployeePK primaryKey);

	/**
	 * Returns the emp_id of this electrotype_ employee.
	 *
	 * @return the emp_id of this electrotype_ employee
	 */
	public long getEmp_id();

	/**
	 * Sets the emp_id of this electrotype_ employee.
	 *
	 * @param emp_id the emp_id of this electrotype_ employee
	 */
	public void setEmp_id(long emp_id);

	/**
	 * Returns the electro_id of this electrotype_ employee.
	 *
	 * @return the electro_id of this electrotype_ employee
	 */
	public long getElectro_id();

	/**
	 * Sets the electro_id of this electrotype_ employee.
	 *
	 * @param electro_id the electro_id of this electrotype_ employee
	 */
	public void setElectro_id(long electro_id);

}