/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package electrostore.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;employees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>electrostore.db.model.impl.EmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>electrostore.db.model.impl.EmployeeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @generated
 */
@ProviderType
public interface EmployeeModel extends BaseModel<Employee> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this employee.
	 *
	 * @return the primary key of this employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee.
	 *
	 * @param primaryKey the primary key of this employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee_id of this employee.
	 *
	 * @return the employee_id of this employee
	 */
	public long getEmployee_id();

	/**
	 * Sets the employee_id of this employee.
	 *
	 * @param employee_id the employee_id of this employee
	 */
	public void setEmployee_id(long employee_id);

	/**
	 * Returns the name of this employee.
	 *
	 * @return the name of this employee
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this employee.
	 *
	 * @param name the name of this employee
	 */
	public void setName(String name);

	/**
	 * Returns the lastname of this employee.
	 *
	 * @return the lastname of this employee
	 */
	@AutoEscape
	public String getLastname();

	/**
	 * Sets the lastname of this employee.
	 *
	 * @param lastname the lastname of this employee
	 */
	public void setLastname(String lastname);

	/**
	 * Returns the midname of this employee.
	 *
	 * @return the midname of this employee
	 */
	@AutoEscape
	public String getMidname();

	/**
	 * Sets the midname of this employee.
	 *
	 * @param midname the midname of this employee
	 */
	public void setMidname(String midname);

	/**
	 * Returns the birthdate of this employee.
	 *
	 * @return the birthdate of this employee
	 */
	public Date getBirthdate();

	/**
	 * Sets the birthdate of this employee.
	 *
	 * @param birthdate the birthdate of this employee
	 */
	public void setBirthdate(Date birthdate);

	/**
	 * Returns the sex of this employee.
	 *
	 * @return the sex of this employee
	 */
	public boolean getSex();

	/**
	 * Returns <code>true</code> if this employee is sex.
	 *
	 * @return <code>true</code> if this employee is sex; <code>false</code> otherwise
	 */
	public boolean isSex();

	/**
	 * Sets whether this employee is sex.
	 *
	 * @param sex the sex of this employee
	 */
	public void setSex(boolean sex);

	/**
	 * Returns the position_id of this employee.
	 *
	 * @return the position_id of this employee
	 */
	public long getPosition_id();

	/**
	 * Sets the position_id of this employee.
	 *
	 * @param position_id the position_id of this employee
	 */
	public void setPosition_id(long position_id);

}