/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package electrostore.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Position service. Represents a row in the &quot;positiontype&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>electrostore.db.model.impl.PositionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>electrostore.db.model.impl.PositionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Position
 * @generated
 */
@ProviderType
public interface PositionModel extends BaseModel<Position> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a position model instance should use the {@link Position} interface instead.
	 */

	/**
	 * Returns the primary key of this position.
	 *
	 * @return the primary key of this position
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this position.
	 *
	 * @param primaryKey the primary key of this position
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the position_id of this position.
	 *
	 * @return the position_id of this position
	 */
	public long getPosition_id();

	/**
	 * Sets the position_id of this position.
	 *
	 * @param position_id the position_id of this position
	 */
	public void setPosition_id(long position_id);

	/**
	 * Returns the name of this position.
	 *
	 * @return the name of this position
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this position.
	 *
	 * @param name the name of this position
	 */
	public void setName(String name);

}