/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package electrostore.db.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Purchase service. Represents a row in the &quot;purchases&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>electrostore.db.model.impl.PurchaseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>electrostore.db.model.impl.PurchaseImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Purchase
 * @generated
 */
@ProviderType
public interface PurchaseModel extends BaseModel<Purchase> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a purchase model instance should use the {@link Purchase} interface instead.
	 */

	/**
	 * Returns the primary key of this purchase.
	 *
	 * @return the primary key of this purchase
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this purchase.
	 *
	 * @param primaryKey the primary key of this purchase
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the purchase_id of this purchase.
	 *
	 * @return the purchase_id of this purchase
	 */
	public long getPurchase_id();

	/**
	 * Sets the purchase_id of this purchase.
	 *
	 * @param purchase_id the purchase_id of this purchase
	 */
	public void setPurchase_id(long purchase_id);

	/**
	 * Returns the purchase_date of this purchase.
	 *
	 * @return the purchase_date of this purchase
	 */
	public Date getPurchase_date();

	/**
	 * Sets the purchase_date of this purchase.
	 *
	 * @param purchase_date the purchase_date of this purchase
	 */
	public void setPurchase_date(Date purchase_date);

	/**
	 * Returns the electronic_id of this purchase.
	 *
	 * @return the electronic_id of this purchase
	 */
	public long getElectronic_id();

	/**
	 * Sets the electronic_id of this purchase.
	 *
	 * @param electronic_id the electronic_id of this purchase
	 */
	public void setElectronic_id(long electronic_id);

	/**
	 * Returns the purchasetype_id of this purchase.
	 *
	 * @return the purchasetype_id of this purchase
	 */
	public long getPurchasetype_id();

	/**
	 * Sets the purchasetype_id of this purchase.
	 *
	 * @param purchasetype_id the purchasetype_id of this purchase
	 */
	public void setPurchasetype_id(long purchasetype_id);

	/**
	 * Returns the employee_id of this purchase.
	 *
	 * @return the employee_id of this purchase
	 */
	public long getEmployee_id();

	/**
	 * Sets the employee_id of this purchase.
	 *
	 * @param employee_id the employee_id of this purchase
	 */
	public void setEmployee_id(long employee_id);

}