/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package electrostore.db.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import electrostore.db.model.Electrotype_Employee;
import electrostore.db.model.Electrotype_EmployeeModel;
import electrostore.db.service.persistence.Electrotype_EmployeePK;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Electrotype_Employee service. Represents a row in the &quot;electrotype_employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>Electrotype_EmployeeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Electrotype_EmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Electrotype_EmployeeImpl
 * @generated
 */
public class Electrotype_EmployeeModelImpl
	extends BaseModelImpl<Electrotype_Employee>
	implements Electrotype_EmployeeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a electrotype_ employee model instance should use the <code>Electrotype_Employee</code> interface instead.
	 */
	public static final String TABLE_NAME = "electrotype_employee";

	public static final Object[][] TABLE_COLUMNS = {
		{"emp_id", Types.BIGINT}, {"electro_id", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("emp_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("electro_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table electrotype_employee (emp_id LONG not null,electro_id LONG not null,primary key (emp_id, electro_id))";

	public static final String TABLE_SQL_DROP =
		"drop table electrotype_employee";

	public static final String ORDER_BY_JPQL =
		" ORDER BY electrotype_Employee.id.emp_id ASC, electrotype_Employee.id.electro_id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY electrotype_employee.emp_id ASC, electrotype_employee.electro_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ELECTRO_ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMP_ID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public Electrotype_EmployeeModelImpl() {
	}

	@Override
	public Electrotype_EmployeePK getPrimaryKey() {
		return new Electrotype_EmployeePK(_emp_id, _electro_id);
	}

	@Override
	public void setPrimaryKey(Electrotype_EmployeePK primaryKey) {
		setEmp_id(primaryKey.emp_id);
		setElectro_id(primaryKey.electro_id);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new Electrotype_EmployeePK(_emp_id, _electro_id);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((Electrotype_EmployeePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Electrotype_Employee.class;
	}

	@Override
	public String getModelClassName() {
		return Electrotype_Employee.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Electrotype_Employee, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Electrotype_Employee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Electrotype_Employee, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Electrotype_Employee)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Electrotype_Employee, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Electrotype_Employee, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Electrotype_Employee)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Electrotype_Employee, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Electrotype_Employee, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Electrotype_Employee, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Electrotype_Employee, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Electrotype_Employee, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<Electrotype_Employee, Object>>();
		Map<String, BiConsumer<Electrotype_Employee, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<Electrotype_Employee, ?>>();

		attributeGetterFunctions.put("emp_id", Electrotype_Employee::getEmp_id);
		attributeSetterBiConsumers.put(
			"emp_id",
			(BiConsumer<Electrotype_Employee, Long>)
				Electrotype_Employee::setEmp_id);
		attributeGetterFunctions.put(
			"electro_id", Electrotype_Employee::getElectro_id);
		attributeSetterBiConsumers.put(
			"electro_id",
			(BiConsumer<Electrotype_Employee, Long>)
				Electrotype_Employee::setElectro_id);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getEmp_id() {
		return _emp_id;
	}

	@Override
	public void setEmp_id(long emp_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_emp_id = emp_id;
	}

	@Override
	public long getElectro_id() {
		return _electro_id;
	}

	@Override
	public void setElectro_id(long electro_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_electro_id = electro_id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalElectro_id() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("electro_id"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Electrotype_Employee toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Electrotype_Employee>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Electrotype_EmployeeImpl electrotype_EmployeeImpl =
			new Electrotype_EmployeeImpl();

		electrotype_EmployeeImpl.setEmp_id(getEmp_id());
		electrotype_EmployeeImpl.setElectro_id(getElectro_id());

		electrotype_EmployeeImpl.resetOriginalValues();

		return electrotype_EmployeeImpl;
	}

	@Override
	public int compareTo(Electrotype_Employee electrotype_Employee) {
		Electrotype_EmployeePK primaryKey =
			electrotype_Employee.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Electrotype_Employee)) {
			return false;
		}

		Electrotype_Employee electrotype_Employee =
			(Electrotype_Employee)object;

		Electrotype_EmployeePK primaryKey =
			electrotype_Employee.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Electrotype_Employee> toCacheModel() {
		Electrotype_EmployeeCacheModel electrotype_EmployeeCacheModel =
			new Electrotype_EmployeeCacheModel();

		electrotype_EmployeeCacheModel.electrotype_EmployeePK = getPrimaryKey();

		electrotype_EmployeeCacheModel.emp_id = getEmp_id();

		electrotype_EmployeeCacheModel.electro_id = getElectro_id();

		return electrotype_EmployeeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Electrotype_Employee, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Electrotype_Employee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Electrotype_Employee, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(Electrotype_Employee)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Electrotype_Employee, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Electrotype_Employee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Electrotype_Employee, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((Electrotype_Employee)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Electrotype_Employee>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Electrotype_Employee.class, ModelWrapper.class);

	}

	private long _emp_id;
	private long _electro_id;

	public <T> T getColumnValue(String columnName) {
		Function<Electrotype_Employee, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Electrotype_Employee)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("emp_id", _emp_id);
		_columnOriginalValues.put("electro_id", _electro_id);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("emp_id", 1L);

		columnBitmasks.put("electro_id", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Electrotype_Employee _escapedModel;

}