/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package electrostore.db.model.impl;

import electrostore.db.model.Electrotype_Employee;
import electrostore.db.service.Electrotype_EmployeeLocalServiceUtil;

/**
 * The extended model base implementation for the Electrotype_Employee service. Represents a row in the &quot;electrotype_employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Electrotype_EmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Electrotype_EmployeeImpl
 * @see Electrotype_Employee
 * @generated
 */
public abstract class Electrotype_EmployeeBaseImpl
	extends Electrotype_EmployeeModelImpl implements Electrotype_Employee {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a electrotype_ employee model instance should use the <code>Electrotype_Employee</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Electrotype_EmployeeLocalServiceUtil.addElectrotype_Employee(this);
		}
		else {
			Electrotype_EmployeeLocalServiceUtil.updateElectrotype_Employee(
				this);
		}
	}

}