/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package electrostore.db.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import electrostore.db.model.Purchase;
import electrostore.db.model.PurchaseModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Purchase service. Represents a row in the &quot;purchases&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PurchaseModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PurchaseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PurchaseImpl
 * @generated
 */
public class PurchaseModelImpl
	extends BaseModelImpl<Purchase> implements PurchaseModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a purchase model instance should use the <code>Purchase</code> interface instead.
	 */
	public static final String TABLE_NAME = "purchases";

	public static final Object[][] TABLE_COLUMNS = {
		{"purchase_id", Types.BIGINT}, {"purchase_date", Types.TIMESTAMP},
		{"electronic_id", Types.BIGINT}, {"purchasetype_id", Types.BIGINT},
		{"employee_id", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("purchase_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("purchase_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("electronic_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("purchasetype_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employee_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table purchases (purchase_id LONG not null primary key,purchase_date DATE null,electronic_id LONG,purchasetype_id LONG,employee_id LONG)";

	public static final String TABLE_SQL_DROP = "drop table purchases";

	public static final String ORDER_BY_JPQL =
		" ORDER BY purchase.purchase_id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY purchases.purchase_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PURCHASE_ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PurchaseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _purchase_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPurchase_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _purchase_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Purchase.class;
	}

	@Override
	public String getModelClassName() {
		return Purchase.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Purchase, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Purchase, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Purchase, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Purchase)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Purchase, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Purchase, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Purchase)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Purchase, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Purchase, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Purchase, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Purchase, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Purchase, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Purchase, Object>>();
		Map<String, BiConsumer<Purchase, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Purchase, ?>>();

		attributeGetterFunctions.put("purchase_id", Purchase::getPurchase_id);
		attributeSetterBiConsumers.put(
			"purchase_id",
			(BiConsumer<Purchase, Long>)Purchase::setPurchase_id);
		attributeGetterFunctions.put(
			"purchase_date", Purchase::getPurchase_date);
		attributeSetterBiConsumers.put(
			"purchase_date",
			(BiConsumer<Purchase, Date>)Purchase::setPurchase_date);
		attributeGetterFunctions.put(
			"electronic_id", Purchase::getElectronic_id);
		attributeSetterBiConsumers.put(
			"electronic_id",
			(BiConsumer<Purchase, Long>)Purchase::setElectronic_id);
		attributeGetterFunctions.put(
			"purchasetype_id", Purchase::getPurchasetype_id);
		attributeSetterBiConsumers.put(
			"purchasetype_id",
			(BiConsumer<Purchase, Long>)Purchase::setPurchasetype_id);
		attributeGetterFunctions.put("employee_id", Purchase::getEmployee_id);
		attributeSetterBiConsumers.put(
			"employee_id",
			(BiConsumer<Purchase, Long>)Purchase::setEmployee_id);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getPurchase_id() {
		return _purchase_id;
	}

	@Override
	public void setPurchase_id(long purchase_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purchase_id = purchase_id;
	}

	@Override
	public Date getPurchase_date() {
		return _purchase_date;
	}

	@Override
	public void setPurchase_date(Date purchase_date) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purchase_date = purchase_date;
	}

	@Override
	public long getElectronic_id() {
		return _electronic_id;
	}

	@Override
	public void setElectronic_id(long electronic_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_electronic_id = electronic_id;
	}

	@Override
	public long getPurchasetype_id() {
		return _purchasetype_id;
	}

	@Override
	public void setPurchasetype_id(long purchasetype_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purchasetype_id = purchasetype_id;
	}

	@Override
	public long getEmployee_id() {
		return _employee_id;
	}

	@Override
	public void setEmployee_id(long employee_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employee_id = employee_id;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Purchase.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Purchase toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Purchase>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PurchaseImpl purchaseImpl = new PurchaseImpl();

		purchaseImpl.setPurchase_id(getPurchase_id());
		purchaseImpl.setPurchase_date(getPurchase_date());
		purchaseImpl.setElectronic_id(getElectronic_id());
		purchaseImpl.setPurchasetype_id(getPurchasetype_id());
		purchaseImpl.setEmployee_id(getEmployee_id());

		purchaseImpl.resetOriginalValues();

		return purchaseImpl;
	}

	@Override
	public int compareTo(Purchase purchase) {
		long primaryKey = purchase.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Purchase)) {
			return false;
		}

		Purchase purchase = (Purchase)object;

		long primaryKey = purchase.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Purchase> toCacheModel() {
		PurchaseCacheModel purchaseCacheModel = new PurchaseCacheModel();

		purchaseCacheModel.purchase_id = getPurchase_id();

		Date purchase_date = getPurchase_date();

		if (purchase_date != null) {
			purchaseCacheModel.purchase_date = purchase_date.getTime();
		}
		else {
			purchaseCacheModel.purchase_date = Long.MIN_VALUE;
		}

		purchaseCacheModel.electronic_id = getElectronic_id();

		purchaseCacheModel.purchasetype_id = getPurchasetype_id();

		purchaseCacheModel.employee_id = getEmployee_id();

		return purchaseCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Purchase, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Purchase, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Purchase, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Purchase)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Purchase, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Purchase, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Purchase, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Purchase)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Purchase>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Purchase.class, ModelWrapper.class);

	}

	private long _purchase_id;
	private Date _purchase_date;
	private long _electronic_id;
	private long _purchasetype_id;
	private long _employee_id;

	public <T> T getColumnValue(String columnName) {
		Function<Purchase, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Purchase)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("purchase_id", _purchase_id);
		_columnOriginalValues.put("purchase_date", _purchase_date);
		_columnOriginalValues.put("electronic_id", _electronic_id);
		_columnOriginalValues.put("purchasetype_id", _purchasetype_id);
		_columnOriginalValues.put("employee_id", _employee_id);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("purchase_id", 1L);

		columnBitmasks.put("purchase_date", 2L);

		columnBitmasks.put("electronic_id", 4L);

		columnBitmasks.put("purchasetype_id", 8L);

		columnBitmasks.put("employee_id", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Purchase _escapedModel;

}